# Generated by Django 4.1.3 on 2022-11-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    
    
    dependencies = [
        ('core', '0002_alter_categoria_options_alter_marca_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('image', models.TextField(verbose_name='Imagen')),
                ('Escudo', models.PositiveIntegerField(verbose_name='Escudo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'Equipo',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Categoría'),
        ),
    ]
