# Generated by Django 4.1.3 on 2022-11-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_team_escudo_remove_team_image_team_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='../static/img', verbose_name='Bandera'),
        ),
    ]
