# Generated by Django 4.1.3 on 2022-11-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team_alter_categoria_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marca',
        ),
        migrations.AlterField(
            model_name='team',
            name='Escudo',
            field=models.ImageField(upload_to='', verbose_name='Escudo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
