# Generated by Django 4.1.3 on 2022-11-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_categoria_remove_product_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Escudo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.AddField(
            model_name='team',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bandera'),
        ),
        migrations.AddField(
            model_name='team',
            name='shield',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Escudo'),
        ),
    ]
