# Generated by Django 4.1.3 on 2022-11-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='description',
        ),
        migrations.AddField(
            model_name='coach',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido'),
        ),
    ]
