# Generated by Django 4.1.3 on 2022-11-04 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_coach_description_coach_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Foto')),
                ('datebirth', models.DateField(verbose_name='Nacimiento')),
                ('number', models.SmallIntegerField(verbose_name='Posición')),
                ('headline', models.BooleanField(verbose_name='Titular')),
                ('position', models.ManyToManyField(to='core.gameposition', verbose_name='Posición')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugadores',
                'ordering': ['id'],
            },
        ),
    ]
